/**
 * Dependencies
 */

import React from 'react'

/**
 * Import styles
 */

import './styles/TermsOfService.scss';

/**
 * Define view
 */

const TermsOfService = () => {
    return(
        <div className='service'>
            <h1>Terms of Use</h1>
            <h3>Thanks for using Brāv.</h3>
            <p>Please read these Terms carefully. By using Brāv or signing up for an account, you’re agreeing to these Terms. This is a legal agreement. We’ll start with the basics, including a few definitions that should help you understand this agreement. Brāv (“Brāv” or the “Service”) is an conflict managing service offered through the URL www.brav.org (aka “Website”) that allows you to among others, train, manage, and vote on various conflicts of yours or other individuals. Brāv is owned and operated by NGM, LP d/b/a Brāv, a Michigan limited partnership (“Brāv,” “we,” or “us”). Brāv has employees, independent contractors, interns, volunteers and representatives (“our Team”). As a customer of the Service or a representative of an entity that’s a customer of the Service, you’re a “Member” according to this agreement (or “you”).
            These Terms of Use (“Terms,” including our Privacy Policy, Acceptable Use Policy, API Guidelines, Copyright Policy and Brand Guidelines) define the terms and conditions under which you’re allowed to use Brāv, and how we’ll treat your account while you’re a Member. If you have any questions about our terms, feel free to contact us.
            ACCOUNT</p>
            <h3>1. Eligibility</h3>
            <p>In order to use Brāv, you must:
            be at least eighteen (18) years old (or have written consent by a legal guardian if a minor) and able to enter into contracts;
            complete the registration process;
            agree to the Terms; and
            provide true, complete, and up to date contact information.
            By using Brāv, you represent and warrant that you meet all the requirements listed above, and that you won’t use Brāv in a way that violates any laws or regulations. (Representing and warranting is like making a legally enforceable promise.) Brāv may refuse service, close accounts of any users, and change eligibility requirements at any time.</p>
            <h3>2. Term</h3>
            <p>The Term begins when you sign up for Brāv and continues as long as you use the Service. Clicking the button and entering your username means that you’ve officially “signed” the Terms. If you sign up for Brāv on behalf of a company or other entity, you represent and warrant that you have the authority to accept these Terms on their behalf.</p>
            <h3>3. Closing Your Account</h3>
            <p>You or Brāv may terminate this Agreement at any time and for any reason by giving Notice to the other party. We may suspend our Service to you at any time, with or without cause. We refuse to refund any amount - this includes no perforated portions or any prepayment, and this includes if we terminate your account with or without cause. Instead, we may at our discretion reimburse you for unused conflict management Credits, but only if requested within ten days of termination. In addition, we won’t refund or reimburse you if there is cause, like a violation of these Terms or our Acceptable Use Policy. Once terminated, we may permanently delete your account and all the data associated with it, including your conflict managements from our Website. If you don’t log in to your account for 12 or more months, we may treat your account as “inactive” and permanently delete the account and all the data associated with it.</p>
            <h3>4. Changes</h3>
            <p>We may change any of the Terms by posting revised Terms of Use on our Website and/or by sending an conflict management to the last conflict management address you gave us. Unless you terminate your account within seven (7) days, the new Terms will be effective immediately and apply to any continued or new use of Brāv. We may change the Website, the Service, or any features of the Service at any time.</p>
            <h3>5. Account and Password</h3>
            <p>You’re responsible for keeping your account name and password confidential. You’re also responsible for any account that you have access to, whether or not you authorized the use. You’ll immediately notify us of any unauthorized use of your accounts. We’re not responsible for any losses due to stolen or hacked passwords. We don’t have access to your current password, and for security reasons, we may only reset your password.</p>
            <h3>6. Account Disputes</h3>
            <p>We don’t know the inner workings of your organization or the nature of your personal and/ or professional relationships, and we don’t arbitrate disputes over who owns an account. You won’t request access to or information about an account that’s not yours, and you’ll resolve any account-related disputes directly with the other party. We decide who owns an account based on the content of the conflict managements in that account, and if multiple people or entities are identified in the content, then we’ll rely on the contact information listed for that account.
            PAYMENT</p>
            <p>7. Monthly or Annual Plans
            Our charges for one time,  monthly or annual plans are posted on our Website and may be changed from time to time. If any part of a month is included in the Term, then payment is due for the full month. Payments are due for any month on the same or closest date to the day you made your first monthly payment (the “Pay Date”). If you go over your sending limit and reach another pricing level, then you’ll have to pay at the higher level on or before the next pay date. If the Term ends before that payment is due, you’ll still be required to make one payment at the higher level.</p>
            <h3>8. Pay as You Go Plans</h3>
            <p>You may buy conflict management Credits to use our Services instead of signing up for a monthly plan. This is explained on the pricing page of our Website. If you choose a Pay as You Go Plan, you’ll still be considered a Member, and other than the monthly payment requirement, all the terms of this Agreement will still apply to you. conflict management Credits for Pay as You Go accounts roll over and don’t expire, but if your account is inactive for more than 12 months, it may be deleted.</p>
            <h3>9. Credit Cards</h3>
            <p>As long as you’re a User/ Member or have an outstanding balance with us, you’ll provide us with valid debit and/ or credit card information and authorize us to deduct the regular (ie/ daily, weekly, monthly, annually, etc) charges against that debit and/ or credit card. You’ll replace the information for any credit card that expires with information for a valid one. Anyone using a debit and/ or credit card represents and warrants that they are authorized to use that debit and/ or credit card, and that any and all charges may be billed to that debit and/ or credit card and won’t be rejected. If we’re unable to process your debit and/ or credit card order, we’ll try to contact you by conflict management and suspend your account until your payment can be processed.</p>
            <h3>10. Refunds</h3>
            <p>You are not entitled to a refund from us under any circumstance. Instead, we may offer Credit towards one service if a User/Member applies for one only if there was absolutely no use of your service and only if requested within seven days of the particular issue, which must be identified and dated within the request.</p>
            <h3>11. Charges for Add-Ons</h3>
            <p>Some features are offered as add-ons to your Brāv account. If you add on a feature that has a charge, then you’ll be billed that additional amount with each billing cycle for as long as the add-on is active. Some add-ons, including the training, are intended for particular use cases and may have additional terms or restrictions (“Additional Terms.”) If you use an add-on in a way that violates these Terms or the Additional Terms, then we may terminate your account. If you use us, in violation of our Acceptable Use Policy, then we may charge you at the comparable Brāv pricing tier or terminate your account.</p>
            <h3>12. Billing Changes</h3>
            <p>We may change our fees at any time by posting a new pricing structure to our Website and/or sending you a notification by email or other means.
            RIGHTS</p>
            <h3>13. Proprietary Rights Owned by Us</h3>
            <p>You will respect our proprietary rights in the Website and the software used to provide Brāv (proprietary rights include patents, trademarks, service marks, trade secrets, and copyrights). You may only use our brand assets according to our Brand Guidelines. Brāv does not accept unsolicited ideas or materials from outside the organization. Should ideas or materials be sent, they will become the sole property of Brāv.</p>
            <h3>14. Proprietary Rights Owned by You</h3>
            <p>You represent and warrant that you either own or have permission to use all of the material in your conflict managements. You retain ownership of the materials that you upload to the Service. We may use or disclose your materials only as described in these Terms and our Privacy Policy. You agree that any and all services may be recorded and retrieved at any time. If any and all parties along with your particular Brāv One(s) agree, your session can be open and left for the public to watch live and/ or rewatch a recorded copy, including any and all materials that you upload to the Services.</p>
            <h3>15. Privacy Policy</h3>
            <p>We may use and disclose your information according to our Privacy Policy. Our Privacy Policy will be treated as part of these Terms</p>

            <h3>16. Right to Review conflict management Campaigns</h3>

            <p>We may view, copy, and internally distribute content from your conflict managements and account to create algorithms and programs (“Tools”) that help us spot problem accounts. We use these Tools to find Members who violate these Terms or laws. For example, We study data internally to make our conflict management Genome Project smarter and create better experiences for senders and subscribers.</p>
            <h1>RULES AND ABUSE</h1>
            <h3>17. General Rules</h3>
            <p>You promise to follow these rules:
            You will not harass and/ or abuse others using the site as defined by U.S. Department of Security.
            You won’t send “spam,” using the definition on the Spamhaus website.
            You will not violate our Acceptable Use Policy, which is part of this Agreement.
            If you use our API, you’ll comply with our API Use Policy.
            If you violate any of these rules, then we may suspend or terminate your account without any possibility of a partial or whole refund.</p>
            <h3>18. Reporting Abuse</h3>
            <p>If you think anyone is violating any of these Terms, please notify us immediately. If you received spam you think came from a Brāv user, please report it to our abuse team. (The best way to tell whether an conflict management was sent through Brāv is that every Brāv campaign has an embedded Campaign Tracking ID in the header that makes it easy to report suspected spam.) If you think anyone has posted material that violates any copyrights, then you can notify us according to our Copyright Policy.</p>
            <h3>19. Bandwidth Abuse/Throttling</h3>
            <p>You may only use our bandwidth for your Brāv conflict managements. We provide image and data hosting only for your conflict management campaigns, so you may not host images on our servers for anything else (like a website). We may throttle your sending or connection through our API at our discretion.</p>
            <h3>20. Compliance with Laws</h3>
            <p>You represent and warrant that your use of Brāv will comply with all applicable laws and regulations. You’re responsible for determining whether our Services are suitable for you to use in light of any regulations like HIPAA, GLB, EU Data Privacy Laws, or other laws. If you’re subject to regulations (like HIPAA) and you use our Service, then we won’t be liable if our Service doesn’t meet those requirements. You may not use our Service for any unlawful or discriminatory activities, including acts prohibited by the Federal Trade Commission Act, Fair Credit Reporting Act, Equal Credit Opportunity Act, or other laws that apply to commerce.</p>
            <p>If you’re located in the European Economic Area (EEA) or send to anyone in the EEA, you represent and warrant that in training, seeking to have a conflict managed, sending communication via Brāv, and collecting information as a result of sending communication, you:
            Will clearly describe in writing how you plan to use any data collected, including for your use of Brāv. You’ll get express consent to transfer data to Brāv and be processed, and you’ll otherwise comply with whatever privacy policy you have posted.</p>
            <p>Have complied, and will comply, with all regulations, as well as data protection, electronic communication, and privacy laws that apply to the countries where you’re sending any form of communication through Brāv.</p>
            <p>Have collected, stored, used, and transferred all data relating to any individual in compliance with all data protection laws and regulations. You have the necessary permission to allow Brāv to receive and process data and send communications to that individual on your behalf.
            Agree to indemnify and hold us harmless from any losses, including attorney fees, that result from your breach of any part of these warranties.</p>
            <p>You agree to only use mediation or arbitration (preferably through the Brāv platform) to manage any and all conflicts and never through court of any jurisdiction.
            Have signed our Data Processing Agreement.</p>
            <h3>21. U.S. Export Controls</h3>
            <p>The software that supports the Services (the “Software”) is subject to United States export controls. Export laws are set up by the government to keep certain goods and services from reaching other countries, usually because of security concerns or trade agreements. None of the Software may be downloaded or otherwise exported or re-exported in violation of United States export laws. You’re downloading and using the Software at your own risk.</p>
            <h1>LIABILITY</h1>
            <h3>22. Limitation of Liability</h3>
            <p>To the maximum extent permitted by law, you assume full responsibility for any loss that results from your use of the Website and the Services, including any downloads from the Website. We and our Team won’t be liable for any indirect, punitive, special, or consequential damages under any circumstances, even if they’re based on negligence or we’ve been advised of the possibility of those damages. Our total liability for all claims made about the Service in any month will be no more than what you paid us for the Service the month before.</p>
            <h3>23. No Warranties, No Guarantees</h3>
            <p>To the maximum extent permitted by law, we provide the material on the Website and the Service as is. That means we don’t provide warranties of any kind, either express or implied, including but not limited to warranties of merchantability and fitness for a particular purpose. Since people use Brāv for a variety of reasons, we can’t guarantee that it will meet your specific needs.
            There are no guarantees of any particular outcome utilizing any aspect of our product and/ or Website.</p>
            <h3>24. Indemnity</h3>
            <p>You agree to indemnify and hold us and our Team harmless from any losses, including attorney fees that result from any claims you make that aren’t allowed under these Terms due to a “Limitation of Liability” or other provision. (Indemnity is an agreement to compensate someone for a loss.) You also agree to indemnify and hold us harmless from any losses, including attorney fees, that result from third-party claims that you or someone using your password did something that, if true, would violate any of these Terms.</p>
            <h3>25. Attorney Fees</h3>
            <p>If we file an action against you claiming you breached these Terms and we prevail, we’re entitled to recover reasonable attorney fees and any damages or other relief we may be awarded.</p>
            <h3>26. Equitable Relief</h3>
            <p>If you violate these Terms then we may seek injunctive relief (meaning we may request a court order to stop you) or other equitable relief.</p>
            <h3>27. Subpoena Fees</h3>
            <p>If we have to provide information in response to a subpoena related to your account, then we may charge you for our costs. These fees may include attorney and employee time spent retrieving the records, preparing documents, and participating in a deposition.</p>
            <h3>28. Disclaimers</h3>
            <p>We and our Team aren’t responsible for the behavior of any advertisers, linked websites, or other Members.</p>
            <h1>FINE PRINT</h1>
            <h3>29. Notice to Brāv End Users</h3>
            <p>The Software and Website, including all documentation, are “Commercial Items,” as that term is defined at 48 C.F.R. §2.101, and consist of “Commercial Computer Software” and “Commercial Computer Software Documentation.” The Commercial Computer Software and Commercial Computer Software Documentation are licensed to Brāv  end users:
            only as Commercial Items,
            with the same rights as all other end users, and
            according to the Terms
            Published and Unpublished rights are reserved under the copyright laws of the United States. Manufacturer is NGM, LP, P.O. Box 36081, Grosse Pointe, Michigan 48236.</p>
            <h3>30. Assignments</h3>
            <p>You may not assign any of your rights under this agreement to anyone else. We may assign our rights to any other individual or entity at our discretion.</p>
            <h3>31. Choice of Law</h3>
            <p>In case of any disputes, you agree that Brāv reserves the right to choose the jurisdiction of Brāv’s choice. If otherwise not stated, the State of Michigan’s laws, except for conflict of laws rules, will apply to any dispute related to these Terms or the Service. Any dispute related to the Terms, the Privacy Policy, or the Service itself will be decided by the state and federal courts in Michigan, or wherever Brāv believes fit and each party will be subject to the jurisdiction of those courts.</p>
            <h3>32. Force Majeure</h3>
            <p>We won’t be held liable for any delays or failure in performance of any part of the Service, from any cause beyond our control. This includes, but is not limited to, acts of God, changes to law or regulations, embargoes, war, terrorist acts, riots, fires, earthquakes, nuclear accidents, zombie apocalypse, floods, strikes, power blackouts, volcanic action, unusually severe weather conditions, and acts of hackers or third-party internet service providers.</p>
            <h3>33. Survivability</h3>
            <p>Even if this Agreement is terminated, the following sections will continue to apply: Proprietary Rights Owned by Us, Proprietary Rights Owned by You, Compliance with Laws, Limitation of Liability, No Warranties, Indemnity, Choice of Law, Severability, and Entire Agreement.</p>
            <h3>34. Severability</h3>
            <p>If it turns out that a section of this Agreement isn’t enforceable, then that section will be removed or edited as little as necessary, and the rest of the Terms will still be valid.</p>
            <h3>35. Interpretation</h3>
            <p>The headers and sidebar text are provided only to make this agreement easier to read and understand. The fact that we wrote these Terms won’t affect the way this Agreement is interpreted.</p>
            <h3>36. Amendments and Waiver</h3>
            <p>Amendments or changes to these Terms won’t be effective until we post revised Terms on the Website. If we don’t immediately take action on a violation of these Terms, we’re not giving up any rights under the Terms, and we may still take action at some point.</p>
            <h3>37. No Changes in Terms at Request of Member</h3>
            <p>Because we have so many Members, we can’t change these Terms for any one Member or group.</p>
            <h3>38. Further Actions</h3>
            <p>You’ll provide all documents and take any actions necessary to meet your obligations under these Terms.</p>
            <h3>39. Notification of Security Breach</h3>
            <p>In the event of a security breach that may affect you or anyone on your conflict management information, we’ll notify you of the breach and provide a description of what happened. If we determine, and notify you, that you need to forward all or part of that information to anyone, you’ll promptly do so.</p>
            <h3>40. Notices</h3>
            <p>Any notice to you will be effective when we send it to the last email you gave us or posted on our Website. Any notice to us will be effective when delivered to us along with a copy to our legal counsel: Attn. Legal Department, Brāv P.O. Box 36081 Grosse Pointe, MI 48236, or any addresses as we may later post on the Website.</p>
            <h3>41. Entire Agreement</h3>
            <p>These Terms, our Privacy Policy, Acceptable Use Policy, API Guidelines (all of which are incorporated into these Terms by reference), and any additional terms you’ve agreed to by turning on specific features (“Additional Terms”) make up the entire agreement and supersede all prior agreements, representations, and understandings. Any Additional Terms will be considered incorporated into these Terms when you activate the feature.</p>
            <p>Where there’s a conflict between these Terms and the Additional Terms, the Additional Terms will control.
            You use Brāv services at your own risk. The services are provided on an “as is” and “as available” basis.</p>
            <p>42. Brāv makes no representations or warranties of any kind with respect to Brāv services. For example, we do not warrant that (i) the service will meet your specific requirements, (ii) the service will be uninterrupted, timely, absolutely secure, or error-free, (iii) the quality of any products, services, information, or other material purchased or obtained by you through the service will meet your expectations, or (iv) any errors in Brāv services will be corrected.</p>
            <p>43. You understand and expressly agree that Brāv shall not be liable for any direct, indirect, incidental, special, consequential or exemplary damages, including, but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses (even if Brāv has been advised of the possibility of such damages), resulting from: (i) the use or the inability to use the service; (ii) the cost of procurement of substitute goods and services resulting from any goods, data, information or services purchased or obtained or messages received or transactions entered into through or from the service; (iii) unauthorized access to or alteration of your transmissions or data; (iv) statements or conduct of any third party on the service; (v) or any other matter relating to Brāv services.</p>
            <p>44. The failure of Brāv to exercise or enforce any right or provision of these terms shall not constitute a waiver of that right or provision. The terms and our privacy policy constitute the entire agreement between you and Brāv and govern your use of Brāv services, superseding any prior agreements between you and Brāv (including, but not limited to, any prior versions of the terms). You agree that these terms and your use of Brāv services are governed under Brāv's choice of law  law. Before resorting to courts, we strongly encourage you to contact us directly to try to work it out.
            If you are ​using ​Brāv for other reasons, certain amendments to ​Brāv’s terms of service ​applies to you​.</p>


            <h1>Brāv Terms of Service</h1>
            <h3>Last Updated Date: June 15, 2019</h3>
            <p>Brāv (“Brāv” or “we”) provides training and an online dispute resolution platform (the “Services”) through our website, accessible at www.brav.org (the “Site”). Please read carefully the following terms and conditions (“Terms”) and our Privacy Policy, which may be found at http://www.brav.org.  These Terms govern your access to and use of the Site, Services and Collective Content (defined below), and constitute a binding legal agreement between you and Brāv. </p>
            <h3>Key Content-related Terms </h3>
            <p>Content means text, graphics, images, music, software, audio, video, information or other materials.
            Brāv Content means Content that Brāv makes available through the Site or Services, including any Content licensed from a third party, but excluding Member Content. </p>
            <p>Member means a person who completes Brāv’s account registration process, as described under the “Account Registration” section below. </p>
            <p>Member Content means Content that a Member posts, uploads, publishes, submits or transmits to be made available through the Site or Services. </p>
            <p>Collective Content means, collectively, Brāv Content and Member Content.</p>
            <p>Certain areas of the Site (and your access to or use of certain Services or Collective Content) may have different terms and conditions posted or may require you to agree with and accept additional terms and conditions. If there is a conflict between these Terms and terms and conditions posted for a specific area of the Site, Services or Collective Content, the latter terms and conditions will take precedence with respect to your use of or access to that area of the Site, Services or Collective Content, as applicable. </p>
            <p>YOU ACKNOWLEDGE AND AGREE THAT, BY ACCESSING OR USING THE SITE OR SERVICES,OR BY UPLOADING OR DOWNLOADING OR POSTING ANY CONTENT FROM OR ON THE SITE OR THROUGH THE SERVICES, YOU ARE INDICATING THAT YOU HAVE READ, AND THAT YOU UNDERSTAND AND AGREE TO BE BOUND BY, THESE TERMS, WHETHER OR NOT YOU HAVE REGISTERED ON OR THROUGH THE SITE. IF YOU DO NOT AGREE TO THESE TERMS, THEN YOU HAVE NO RIGHT TO ACCESS OR USE THE SITE, SERVICES OR COLLECTIVE CONTENT. If you accept or agree to these Terms on behalf of an Organization or other legal entity, you represent and warrant that you have the authority to bind that Organization or other legal entity to these Terms and, in such event, “you” and “your” will refer and apply to that Organization or other legal entity. </p>
            <h3>Modification</h3>
            <p>Brāv reserves the right, at its sole discretion, to modify, discontinue or terminate the Site or Services or to modify these Terms, at any time and without prior notice. If we modify these Terms we will post the modification on the Site or provide you with notice of the modification. We will also update the “Last Updated Date” at the top of these Terms. By continuing to access or use the Site or Services after we have posted a modifica
            tion on the Site or have provided you with notice of a modification, you are indicating that you agree to be bound by the modified Terms. If the modified Terms are not acceptable to you, your only recourse is to cease using the Site and Services. </p>
            <h3>Eligibility </h3>
            <p>The Site and Services are intended solely for persons who are 18 or older. Any access to or use of the Site or Services by anyone under 18 is expressly prohibited. By accessing or using the Site or Services you represent and warrant that you are 18 or older.
            Using Brāv </p>
            <p>Via the Site and Services, Members can utilize the tools made available by Brāv to resolve disputes with other Members and third parties (“Disputes”). If you file a Dispute via the Site and Services, we will attempt to contact and encourage the other party to the Conflict to respond to your filing. You can then try to settle your Conflict through the Site and Services. If you are unable to resolve a dispute by communicating with a party independently via the Site and Services, Members can choose to access the services of third party neutrals such as arbitrators and dispute resolution experts to help manage conflicts “Neutrals”). Use of a Neutral may incur additional fees. Please see http://Brāv.org/contact/ for more information on fees for use of the Site and Services. If a resolution cannot be reached through the use of a Neutral, the Neutral will recommend a solution. Members can also upload Member Content related to disputes and share such Member Content with other Members or Neutrals by making selections via the Site and Services. </p>
            <p>Please note that the Site and Services are merely a platform to assist Members in resolving Disputes, and Brāv is not a party to any disputes between Members or between Members and third parties. Brāv does not guarantee that any and/ or all disputes will be resolved through the use of the Site or Services. ACCORDINGLY, YOU UNDERSTAND AND AGREE THAT Brāv WILL HAVE NO LIABILITY RELATED TO DISPUTES AND DISCLAIMS ANY AND ALL LIABILITY IN THIS REGARD. </p>
            <h3>Account Registration </h3>
            <p>In order to access certain features of the Site and Services and to post any Member Content on the Site or through the Services you must register to create an account (“Account”) and become a Member. You agree to provide accurate, current and complete information during the registration process and to update such information to keep it accurate, current and complete. Brāv reserves the right to suspend or terminate your Account if any information provided during the registration process or thereafter proves to be inaccurate, not current or incomplete. You are responsible for safeguarding your password. You agree that you will not disclose your password to any third party and that you will take sole responsibility for any activities or actions under your Account, whether or not you have authorized such activities or actions. You will immediately notify Brāv of any unauthorized use of your Account. </p>
            <h3>Account Information and Payment Terms</h3>
            <p>Brāv makes certain features of the Services available without charge. However, if you choose to utilize any paid features of the Services, you authorize Brāv or its third party payment processor to charge your method of payment in the amount of any paid features of the Services that you choose to utilize. More information related to paid features of the Services is accessible at http:/Brāv.org/. In connection with such paid features, when you register for an Account, you may be required to provide customary billing information such as name and billing address. You agree to pay the applicable fees and any taxes and other fees that may accrue in relation to your use of the Site and Services, if any. All fees are non-refundable and non-transferable. All fees and applicable taxes, if any, are payable in United States dollars. </p>
            <h3>Privacy </h3>
            <p>See Brāv’s Privacy Policy at http:/www.brav.org/ for information and notices concerning Brāv’s collection and use of your personal information.
            Ownership </p>
            <p>The Site, Services and Collective Content are protected by copyright, trademark, and other laws of the United States and foreign countries. You acknowledge and agree that the Site, Services and Brāv Content, including all associated intellectual property rights, are the exclusive property of Brāv and its licensors. You will not remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Site, Services or Collective Content.
            Licenses Granted by Brāv to Brāv Content and Member Content </p>
            <p>Subject to your compliance with the terms and conditions of these Terms, Brāv grants you a limited, non-exclusive, non-transferable license: (i) to view, download and print any Brāv Content solely for your personal and non-commercial purposes; and (ii) a to view any Member Content of other Members to which you are permitted access solely for your internal purposes. You have no right to sublicense the license rights granted in this section. </p>
            <p>You will not use, copy, adapt, modify, prepare derivative works based upon, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast or otherwise exploit the Site, Services or Collective Content, except as expressly permitted in these Terms. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by Brāv or its licensors, except for the licenses and rights expressly granted in these Terms. </p>
            <h3>License granted by Member </h3>
            <p>We may, in our sole discretion, permit Members to post, upload, publish, submit or transmit Member Content. By making available any Member Content on or through the Site or Services, you hereby grant to Brāv a worldwide, irrevocable, perpetual, non-exclusive, transferable, royalty-free license, with the right to sublicense, to use, view, copy, adapt, transfer, publicly display, publicly perform, transmit, stream, broadcast and otherwise exploit such Member Content only on, through or by means of the Site or Services and only in the course of providing the Site and Services., Brāv does not claim any ownership rights in any Member Content and nothing in these Terms will be deemed to restrict any rights that you may have to use and exploit any Member Content. </p>
            <p>You acknowledge and agree that you are solely responsible for all Member Content that you make available through the Site or Services. Accordingly, you represent and warrant that: (i) you either are the sole and exclusive owner of all Member Content that you make available through the Site or Services or you have all rights, licenses, consents and releases that are necessary to grant to Brāv and to the rights in such Member Content, as contemplated under these Terms; and (ii) neither the Member Content nor your posting, uploading, publication, submission or transmittal of the Member Content or Brāv’s use of the Member Content (or any portion thereof) on, through or by means of the Site or Services will infringe, misappropriate or violate a third party’s patent, copyright, trademark, trade secret, moral rights or other intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation. </p>
            <h3>Feedback </h3>
            <p>We welcome and encourage you to provide feedback, comments and suggestions for improvements to the Site or Services (“Feedback”). You may submit Feedback by emailing us at info@Brāv.org or through the www.Brāv.org section of the Site. You acknowledge and agree that if you submit any Feedback to us, you hereby grant to us a non-exclusive, worldwide, perpetual, irrevocable, fully-paid, royalty-free, sub-licensable and transferable license under any and all intellectual property rights that you own or control to use, copy, modify, create derivative works based upon and otherwise exploit the Feedback for any purpose. </p>
            <h3>General Prohibitions</h3>
            <h4>You agree not to do any of the following:</h4>
            <p>Post, upload, publish, submit or transmit any Content that: (i) infringes, misappropriates or violates a third party’s patent, copyright, trademark, trade secret, moral rights or other intellectual property rights, or rights of publicity or privacy; (ii) violates, or encourages any conduct that would violate, any applicable law or regulation or would give rise to civil liability; (iii) is fraudulent, false, misleading or deceptive; (iv) is defamatory, obscene, pornographic, vulgar or offensive; (v) promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; (vi) is violent or threatening or promotes violence or actions that are threatening to any person or entity; or (vii) promotes illegal or harmful activities or substances.</p>
            <h3>Acknowledge</h3>
            <p>Please understand that a dispute may or may not be fully resolved. There are other options including simply managing an escalation, seeking another neutral to resolve or contacting your organization to use existing policies in place.</p>
            <p>Use, display, mirror or frame the Site, or any individual element within the Site or Services, Brāv’s name, any Brāv trademark, logo or other proprietary information, or the layout and design of any page or form contained on a page, without Brāv’s express written consent;
            Access, tamper with, or use non-public areas of the Site, Brāv’s computer systems, or the technical delivery systems of Brāv’s providers;
            Attempt to probe, scan, or test the vulnerability of any Brāv system or network or breach any security or authentication measures;
            Avoid, bypass, remove, deactivate, impair, descramble or otherwise circumvent any technological measure implemented by Brāv or any of Brāv’s providers or any other third party (including another user) to protect the Site, Services or Collective Content;
            Attempt to access or search the Site, Services or Collective Content or download Collective Content from the Site or Services through the use of any engine, software, tool, agent, device or mechanism (including spiders, robots, crawlers, data mining tools or the like) other than the software and/or search agents provided by Brāv or other generally available third party web browsers;
            Send any unsolicited or unauthorized advertising, promotional materials, email, junk mail, spam, chain letters or other form of solicitation;
            Use any meta tags or other hidden text or metadata utilizing a Brāv trademark, logo URL or product name without Brāv’s express written consent;
            Forge any TCP/IP packet header or any part of the header information in any email or newsgroup posting, or in any way use the Site, Services or Collective Content to send altered, deceptive or false source-identifying information;
            Attempt to decipher, decompile, disassemble or reverse engineer any of the software used to provide the Site, Services or Collective Content;
            Interfere with, or attempt to interfere with, the access of any user, host or network, including, without limitation, sending a virus, overloading, flooding, spamming, or mail-bombing the Site or Services;
            Collect or store any personally identifiable information from the Site or Services from other users of the Site or Services without their express permission;
            Impersonate or misrepresent your affiliation with any person or entity;
            Violate any applicable law or regulation;
            Use the identity of any third party; or
            Encourage or enable any other individual to do any of the foregoing.
            Brāv will have the right to investigate violations of any of the above to the fullest extent of the law. Brāv may involve and cooperate with law enforcement authorities in prosecuting users who violate these Terms. You acknowledge that Brāv has no obligation to monitor your access to or use of the Site, Services or Collective Content or to review or edit any Collective Content, but has the right to do so for the purpose of operating the Site and Services, to ensure your compliance with these Terms, or to comply with applicable law or the order or requirement of a court, administrative agency or other governmental body. Brāv reserves the right, at any time and without prior notice, to remove or disable access to any Collective Content that Brāv, at its sole discretion, considers to be in violation of these Terms or otherwise harmful to the Site or Services.</p>
            <h3>Copyright Policy</h3>
            <p>Brāv respects copyright law and expects its users to do the same. It is Brāv’s policy to terminate in appropriate circumstances Members or other account holders who repeatedly infringe or are believed to be repeatedly infringing the rights of copyright holders. Please see Brāv’s Copyright Policy at Brāv.org for further information.</p>
            <h3>Links </h3>
            <p>The Site or Services may contain links to third-party websites or resources. You acknowledge and agree that Brāv is not responsible or liable for: (i) the availability or accuracy of such websites or resources; or (ii) the content, products, or services on or available from such websites or resources. Links to such websites or resources do not imply any endorsement by Brāv of such websites or resources or the content, products, or services available from such websites or resources. You acknowledge sole responsibility for and assume all risk arising from your use of any such websites or resources or the Content, products, or services on or available from such websites or resources.
            Termination and Account Cancellation </p>
            <p>If you breach any of these Terms, Brāv will have the right to suspend or disable your Account or terminate these Terms, at its sole discretion and without prior notice to you. Brāv reserves the right to revoke your access to and use of the Site, Services and Collective Content at any time, with or without cause. In the event Brāv terminates these Terms for your breach, you will remain liable for all amounts due hereunder. You may cancel your Account at any time by sending an email to info@Brāv.com. </p>
            <h3>Disclaimers </h3>
            <p>THE SITE, SERVICES, PRODUCTS AND/ OR COLLECTIVE CONTENT ARE PROVIDED “AS IS”, WITHOUT WARRANTY OR GUARANTEE OF ANY KIND, EITHER EXPRESS OR IMPLIED. WITHOUT LIMITING THE FOREGOING, Brāv EXPLICITLY DISCLAIMS ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. Brāv MAKES NO WARRANTY THAT THE SITE, SERVICES OR COLLECTIVE CONTENT WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE ON AN UNINTERRUPTED, SECURE, OR ERROR-FREE BASIS. Brāv MAKES NO WARRANTY REGARDING THE QUALITY OF ANY PRODUCTS, SERVICES OR COLLECTIVE CONTENT PURCHASED OR OBTAINED THROUGH THE SITE OR SERVICES OR THE ACCURACY, TIMELINESS, TRUTHFULNESS, COMPLETENESS OR RELIABILITY OF ANY CONTENT OBTAINED THROUGH THE SITE OR SERVICES. Brāv DISCLAIMS ANY AND ALL LIABILITY RELATED TO INTERACTIONS WITH OR ACTIONS OF ANY NEUTRALS. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM Brāv OR THROUGH THE SITE, SERVICES OR COLLECTIVE CONTENT, WILL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN. YOU ARE SOLELY RESPONSIBLE FOR ALL OF YOUR COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE SITE AND SERVICES AND WITH OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE SITE OR SERVICES. YOU UNDERSTAND THAT Brāv DOES NOT SCREEN OR INQUIRE INTO THE BACKGROUND OF ANY USERS OF THE SITE OR SERVICES, NOR DOES Brāv MAKE ANY ATTEMPT TO VERIFY THE STATEMENTS OF USERS OF THE SITE OR SERVICES. Brāv MAKES NO REPRESENTATIONS OR WARRANTIES AS TO THE CONDUCT OF USERS OF THE SITE OR SERVICES OR THEIR COMPATIBILITY WITH ANY CURRENT OR FUTURE USERS OF THE SITE OR SERVICES. YOU AGREE TO TAKE REASONABLE PRECAUTIONS IN ALL COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE SITE AND SERVICES AND WITH OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE SITE OR SERVICES, PARTICULARLY IF YOU DECIDE TO MEET OFFLINE OR IN PERSON. </p>
            <h3>Indemnity </h3>
            <p>You agree to defend, indemnify, and hold Brāv, its officers, directors, employees and agents, harmless from and against any claims, liabilities, damages, losses, and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with your access to or use of the Site, Services or Collective Content, or your violation of these Terms. </p>
            <h3>Limitation of Liability </h3>
            <p>YOU ACKNOWLEDGE AND AGREE THAT, TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE ENTIRE RISK ARISING OUT OF YOUR ACCESS TO AND USE OF THE SITE, SERVICES AND COLLECTIVE CONTENT REMAINS WITH YOU. NEITHER Brāv NOR ANY OTHER person or entity involved in creating, producing, or delivering the Site, Services or Collective Content will be liable for any incidental, special, exemplary or consequential damages, INCLUDING LOST PROFITS, LOSS OF DATA OR LOSS OF GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE OR THE COST OF SUBSTITUTE PRODUCTS OR SERVICES, OR FOR ANY DAMAGES FOR PERSONAL OR BODILY INJURY OR EMOTIONAL DISTRESS arising out of or in connection with thESE TERMS or from the use OF or inability to use the Site, Services or Collective Content, [OR FROM ANY COMMUNICATIONS, INTERACTIONS OR MEETINGS WITH OTHER USERS OF the SITE OR SERVICES OR OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE SITE OR SERVICES whether based on warranty, contract, tort (including negligence), PRODUCT LIABILITY or any and all other legal theory, and whether or not Brāv has been informed of the possibility of such damage, EVEN IF A limited REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PUrPOSE. In no event will Brāv’S aggregate liability arising out of or in connection with THESE TERMS OR FROM THE USE OF OR INABILITY TO USE THE SITE, SERVICES OR COLLECTIVE CONTENT, INCLUDING INTERACTIONS WITH OR ACTIONS OF ANY NEUTRALS, EXCEED THE AMOUNTS YOU HAVE PAID TO Brāv FOR USE OF THE SITE, SERVICES OR COLLECTIVE CONTENT IN THE TWELVE (12) MONTH PERIOD PRIOR TO THE CLAIM GIVING RISE TO LIABILITY, IF YOU HAVE MADE ANY PAYMENTS TO Brāv, OR ONE HUNDRED DOLLARS ($100), IF YOU HAVE NOT MADE ANY PAYMENTS TO Brāv, AS APPLICABLE. THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN Brāv AND YOU. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</p>
            <h3>Proprietary Rights Notices</h3>
            <p>All trademarks, service marks, logos, trade names and any other proprietary designations of Brāv used herein are trademarks or registered trademarks of Brāv. Any other trademarks, service marks, logos, trade names and any other proprietary designations are the trademarks or registered trademarks of their respective parties. </p>
            <h3>Controlling Law and Jurisdiction </h3>
            <p>These Terms and any action related thereto will be governed by Brāv’s Choice of law or the laws of the State of Michigan without regard to its conflict of laws provisions. The exclusive jurisdiction and venue of any action to prevent the actual or threatened infringement, misappropriation or violation of a party’s copyrights, trademarks, trade secrets, patents or other intellectual property rights will be the state and federal courts located in Brāv’s Choice of Law/ Jurisdiction or Michigan and each of the parties hereto waives any objection to jurisdiction and venue in such courts.</p>
            <h3>Entire Agreement</h3>
            <p>These Terms constitute the entire and exclusive understanding and agreement between Brāv and you regarding the Site, Services and Collective Content, and these Terms supersede and replace any and all prior oral or written understandings or agreements between Brāv and you regarding the Site, Services and Collective Content.</p>
            <h3>Assignment</h3>
            <p>You may not assign or transfer these Terms, by operation of law or otherwise, without Brāv’s prior written consent. Any attempt by you to assign or transfer these Terms, without such consent, will be null and of no effect. Brāv may assign or transfer these Terms, at its sole discretion, without restriction. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their successors and permitted assigns.</p>
            <h3>Notices </h3>
            <p>Any notices or other communications permitted or required hereunder, including those regarding modifications to these Terms, will be in writing and given: (i) by Brāv via email (in each case to the address that you provide); or (ii) by posting to the Site. For notices made by e-mail, the date of receipt will be deemed the date on which such notice is transmitted.
            Dispute Resolution </p>
            <p>You and Brāv agree that any and all conflict and/ or dispute, claim or controversy arising out of or relating to these Terms or the breach, termination, enforcement, interpretation or validity thereof or the use of the Site or Services (collectively, “Disputes”) will be settled by binding mediation and/ or arbitration only, and that you do not retain the right to bring an individual action in small claims court and the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of a party’s copyrights, trademarks, trade secrets, patents or other intellectual property rights. You acknowledge and agree that you and Brāv are each waiving the right to a trial by jury or to participate as a plaintiff or class member in any purported class action or representative proceeding. Further, unless both you and Brāv otherwise agree in writing, the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of any class or representative proceeding. If this specific paragraph is held unenforceable, then the entirety of this “Dispute Resolution” section will be deemed void. Except as provided in the preceding sentence, this “Dispute Resolution” section will survive any termination of these Terms. Any legal dispute with Brāv must be resolved through a private mediation or arbitration process out of public view and requires all cases to be brought individually.</p>
            <h3>Fees</h3>
            <p>You agree to be charged fees to extend the use of Brāv service(s) if the deadline expires or time lapses. This may occur for any Brāv service, including but not limited to Brāv training, Brāv sessions(s), Brāv voting, etc.</p>
            <h3>Arbitration Rules and Governing Law </h3>
            <p>The arbitration will be administered by the International Institute for Conflict Prevention and Resolution (“CPR”) in accordance with the Commercial ADR Rules then in effect, except as modified by this “Dispute Resolution” section. (The ADR Rules are available <a href='http://cpradr.org/Resources/ADRTools/ADRRulesEthicsCodes.aspx'>here</a> or by calling CPR at 212-849-6490.) The Federal Arbitration Act will govern the interpretation and enforcement of this Section.</p>
            <h3>Arbitration Process </h3>
            <p>A party who desires to initiate arbitration must provide the other party with a notice of arbitration as specified in the CPR Rules. The arbitrator will be either a retired judge or an attorney licensed to practice law in the state of Brāv's choice of law and will be selected by the parties from the CPR’s roster of consumer dispute arbitrators. If the parties are unable to agree upon an arbitrator within seven (7) days of delivery of the notice of arbitration, then the CPR will appoint the arbitrator in accordance with the CPR Rules.</p>
            <h3>Arbitration Location and Procedure</h3>
            <p>Unless you and Brāv otherwise agree, the arbitration will be conducted in the county where you reside. If your claim does not exceed $10,000, then the arbitration will be conducted solely on the basis of documents you and Brāv submit to the arbitrator, unless you request a hearing or the arbitrator determines that a hearing is necessary. If your claim exceeds $10,000, your right to a hearing will be determined by the CPR Rules. Subject to the CPR Rules, the arbitrator will have the discretion to direct a reasonable exchange of information by the parties, consistent with the expedited nature of the arbitration.</p>
            <h3>Arbitrator’s Decision</h3>
            <p>The arbitrator will render an award within the time frame specified in the CPR Rules. The arbitrator’s decision will include the essential findings and conclusions upon which the arbitrator based the award. Judgment on the arbitration award may be entered in any court having jurisdiction thereof. The arbitrator’s award damages must be consistent with the terms of the “Limitation of Liability” section above as to the types and the amounts of damages for which a party may be held liable. The arbitrator may award declaratory or injunctive relief only in favor of the claimant and only to the extent necessary to provide relief warranted by the claimant’s individual claim. If you prevail in arbitration you will be entitled to an award of attorneys’ fees and expenses, to the extent provided under applicable law. Brāv will not seek, and hereby waives all rights it may have under applicable law to recover, attorneys’ fees and expenses if it prevails in arbitration.</p>
            <h3>Fees </h3>
            <p>Your responsibility to pay any CPR filing, administrative and arbitrator fees will be solely as set forth in the CPR Rules. However, if your claim for damages does not exceed $75,000, Brāv will pay all such fees unless the arbitrator finds that either the substance of your claim or the relief sought in your Demand for Arbitration was frivolous or was brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)).</p>
            <h3>Changes </h3>
            <p>Notwithstanding the provisions of the “Modification” section above, if Brāv changes this “Dispute Resolution” section after the date you first accepted these Terms (or accepted any subsequent changes to these Terms), you may reject any such change by sending us written notice (including by email to info@brav.org) within 30 days of the date such change became effective, as indicated in the “Last Updated Date” above or in the date of Brāv’s email to you notifying you of such change. By rejecting any change, you are agreeing that you will arbitrate any Dispute between you and Brāv in accordance with the provisions of this “Dispute Resolution” section as of the date you first accepted these Terms (or accepted any subsequent changes to these Terms).</p>
            <h3>General</h3>
            <p>The failure of Brāv to enforce any right or provision of these Terms will not constitute a waiver of future enforcement of that right or provision. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of Brāv. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise. If for any reason a court of competent jurisdiction finds any provision of these Terms invalid or unenforceable, that provision will be enforced to the maximum extent permissible and the other provisions of these Terms will remain in full force and effect.</p>
            <h3>Contacting Us</h3>
            <a href='info@brav.org'>Brav</a>
            {/* Twitter Facebook LinkedIn YouTube
            Product
            Brāv Platform
            Features
            How It Works
            Frequently Asked Questions
            Get a Free Demo
            Brāv
            About Us
            Resources
            Brāv Blog
            Jobs
            Contact Us  */}
            <p>Copyright © 2016 · 2006 - 2019, NGM, LP. All Rights Reserved | Copyright Policy | Terms of Service |</p>
        </div>
    )
}

/**
 * Export view
 */

export default TermsOfService;
